ABUNavigator:
  ros__parameters:
    i2c_bus_number: 1
    TOF_front_EN:  13
    TOF_left_EN:   19
    TOF_right_EN:  26

    twist_output_topic: "/cmd_vel"
    
    motion_A1A2_period: 142
    motion_A1A2_velocity: 0.3

    motion_A2A3_period: 68
    motion_A2A3_velocity: 0.5

    motion_A2A2_max_velocity: 0.45
    motion_A2A2_min_velocity: 0.3
    motion_A2A2_Kp: 0.0008
    
    motion_A2RED_normal_velocity: 0.45
    motion_A2RED_slow_velocity: 0.3
    motion_A2RED_Kt: 18

    motion_A2BLU_normal_velocity: 0.45
    motion_A2BLU_slow_velocity: 0.3
    motion_A2BLU_Kt: 18
